name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, ghc: 9.2.1 }
          - { os: ubuntu-20.04, ghc: 9.0.1 }
          - { os: ubuntu-20.04, ghc: 8.10.7 }
          - { os: macos-11, ghc: 9.2.1 }
          - { os: windows-2019, ghc: 9.2.1 }
          - { os: ubuntu-20.04, ghc: 8.8.4 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0
      - run: cabal configure --enable-tests --flags pedantic --jobs --test-show-details direct
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test
      - run: cabal sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist-newstyle/sdist/burrito-*.tar.gz
          name: burrito-${{ github.sha }}.tar.gz
      - run: cabal check
      - if: github.event_name == 'release' && matrix.os == 'ubuntu-20.04' && matrix.ghc == '9.0.1'
        run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' dist-newstyle/sdist/burrito-*.tar.gz
